import { FileUp, MessageSquareText, SearchCheck, Waypoints } from "lucide-react";

import { CheckList, CtaSection, PageHero, PrimaryLink, SecondaryLink, SectionIntro } from "@/components/public-site/public-elements";
import { PublicShell } from "@/components/public-site/public-shell";
import { publicMetadata } from "@/lib/public-metadata";

export const metadata = publicMetadata("Für Unternehmen", "Forderungen strukturiert übergeben und den Bearbeitungsstand mit payveo nachvollziehen.", "/fuer-unternehmen");

const steps = [[FileUp,"Forderung übergeben","Bestehende Mandanten erfassen neue Aufträge geschützt über das Mandantenportal."],[SearchCheck,"Prüfen und einordnen","Daten, Forderungsgrund und Bearbeitungsstand werden strukturiert zusammengeführt."],[MessageSquareText,"Bearbeitung begleiten","Kommunikation, Zahlungen und weitere Schritte werden fallbezogen dokumentiert."],[Waypoints,"Status nachvollziehen","Mandanten können freigegebene Vorgänge und ihren Bearbeitungsstand einsehen."]] as const;

export default function CompaniesPage(){return <PublicShell><PageHero description="payveo unterstützt Unternehmen dabei, offene Forderungen geordnet zu übergeben, professionell bearbeiten zu lassen und den weiteren Verlauf transparent nachzuvollziehen." eyebrow="Für Unternehmen" title="Ein klarer Prozess für offene Forderungen"><PrimaryLink href="/portal/login">Zum Mandantenportal</PrimaryLink><SecondaryLink href="/kontakt">Zusammenarbeit anfragen</SecondaryLink></PageHero><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><SectionIntro description="Von der Übergabe bis zur weiteren Bearbeitung bleibt der Vorgang klar gegliedert. Technische Details treten in den Hintergrund – entscheidend sind vollständige Angaben, dokumentierte Schritte und ein verständlicher Status." eyebrow="Zusammenarbeit" title="So läuft die Bearbeitung grundsätzlich ab" /><div className="mt-14 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{steps.map(([Icon,title,text],index)=><article className="rounded-3xl border border-slate-200 p-7" key={title}><div className="flex items-center justify-between"><Icon className="size-6 text-[#007FC5]" /><span className="text-sm font-semibold text-slate-400">0{index+1}</span></div><h2 className="mt-8 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></section><section className="bg-[#f5f9fc]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:items-center lg:py-28"><SectionIntro description="Der geschützte Zugang ist der zentrale Weg für die digitale Zusammenarbeit mit bestehenden Mandanten." eyebrow="Mandantenportal" title="Vorgänge übermitteln und Bearbeitung einsehen" /><div className="rounded-3xl bg-white p-8 shadow-sm ring-1 ring-slate-200"><CheckList items={["Neue Inkassoaufträge mit Forderungs- und Schuldnerdaten übermitteln","Bearbeitungsstatus vorhandener Vorgänge einsehen","Vorgänge und wesentliche Informationen nachvollziehen"]}/><div className="mt-8"><PrimaryLink href="/portal/login">Zum Mandantenportal</PrimaryLink></div></div></div></section><CtaSection description="Wenn bereits Zugangsdaten vorliegen, können Forderungen direkt über den geschützten Mandantenbereich übermittelt werden." primary={["Mandantenportal öffnen","/portal/login"]} secondary={["Kontaktwege","/kontakt"]} title="Bereit für eine strukturierte Übergabe?" /></PublicShell>}
