import { Injectable, NotFoundException } from "@nestjs/common";
import { DocumentStatus, LedgerEntrySide, LedgerEntryStatus, LedgerEntryType, PaymentAllocationStatus, PortalVisibility, Prisma } from "@prisma/client";
import { PortalPreviewService } from "../portal-preview/portal-preview.service";
import { LocalDocumentStorage } from "../documents/local-document-storage";
import { PrismaService } from "../prisma/prisma.service";

const costTypes = new Set<LedgerEntryType>([LedgerEntryType.COLLECTION_FEE, LedgerEntryType.EXPENSE, LedgerEntryType.COURT_COST, LedgerEntryType.ENFORCEMENT_COST]);
@Injectable()
export class PortalService {
  constructor(private readonly prisma: PrismaService, private readonly previews: PortalPreviewService, private readonly storage: LocalDocumentStorage) {}
  async clientSummary(token?: string) { const context = await this.previews.require(token, "CLIENT"); const cases = await this.clientCases(context.tenantId, context.partyId); return { clientName: (await this.party(context.partyId, context.tenantId)).displayName, total: cases.length, open: cases.filter((item) => item.status === "OPEN").length, closed: cases.filter((item) => item.status !== "OPEN").length, principalTotal: cases.reduce((sum, item) => sum.plus(item.claim?.principalAmount ?? 0), new Prisma.Decimal(0)).toFixed(2), recentCases: cases.slice(0, 5) }; }
  async clientCasesRequest(token?: string) { const context = await this.previews.require(token, "CLIENT"); return this.clientCases(context.tenantId, context.partyId); }
  async clientCase(id: string, token?: string) { const context = await this.previews.require(token, "CLIENT"); const item = await this.clientCaseRecord(id, context.tenantId, context.partyId); return { ...item, ledger: await this.ledgerSummary(id, context.tenantId), documents: await this.documents(id, context.tenantId, [PortalVisibility.CLIENT, PortalVisibility.BOTH]) }; }
  async debtorSummary(token?: string) { const context = await this.previews.require(token, "DEBTOR"); const caseId = await this.debtorCase(context); const item = await this.debtorCaseRecord(caseId, context.tenantId, context.partyId); return { caseNumber: item.caseNumber, clientName: item.clientParty.displayName, claim: item.claim ? { principalAmount: item.claim.principalAmount.toFixed(2), currency: item.claim.currency } : null, ledger: await this.ledgerSummary(caseId, context.tenantId), paymentInformation: await this.paymentInformation(context.tenantId, item.caseNumber) }; }
  async debtorClaim(token?: string) { const context = await this.previews.require(token, "DEBTOR"); return this.ledgerSummary(await this.debtorCase(context), context.tenantId); }
  async debtorDocuments(token?: string) { const context = await this.previews.require(token, "DEBTOR"); return this.documents(await this.debtorCase(context), context.tenantId, [PortalVisibility.DEBTOR, PortalVisibility.BOTH]); }
  async context(token?: string) { return this.previews.context(token); }
  async downloadDocument(id: string, token?: string) { const context = await this.previews.context(token); const document = await this.prisma.caseDocument.findFirst({ where: { id, tenantId: context.portalType === "CLIENT" ? (await this.previews.require(token, "CLIENT")).tenantId : (await this.previews.require(token, "DEBTOR")).tenantId, status: { not: DocumentStatus.VOIDED }, portalVisibility: { in: context.portalType === "CLIENT" ? [PortalVisibility.CLIENT, PortalVisibility.BOTH] : [PortalVisibility.DEBTOR, PortalVisibility.BOTH] }, case: context.portalType === "CLIENT" ? { clientPartyId: (await this.previews.require(token, "CLIENT")).partyId } : { debtorPartyId: (await this.previews.require(token, "DEBTOR")).partyId } }, select: { filename: true, mimeType: true, storageKey: true } }); if (!document) throw new NotFoundException("Dokument wurde nicht gefunden."); return { filename: document.filename, mimeType: document.mimeType, buffer: await this.storage.read(document.storageKey) }; }
  private async clientCases(tenantId: string, partyId: string) { return this.prisma.case.findMany({ where: { tenantId, clientPartyId: partyId, deletedAt: null }, select: { id: true, caseNumber: true, status: true, phase: true, openedAt: true, updatedAt: true, claim: { select: { invoiceNumber: true, principalAmount: true, currency: true } }, debtorParty: { select: { displayName: true } } }, orderBy: { updatedAt: "desc" } }); }
  private async clientCaseRecord(id: string, tenantId: string, partyId: string) { const item = await this.prisma.case.findFirst({ where: { id, tenantId, clientPartyId: partyId, deletedAt: null }, select: { id: true, caseNumber: true, status: true, phase: true, openedAt: true, updatedAt: true, claim: { select: { invoiceNumber: true, invoiceDate: true, principalAmount: true, currency: true } }, debtorParty: { select: { displayName: true } } } }); if (!item) throw new NotFoundException("Inkassoakte wurde nicht gefunden."); return item; }
  private async debtorCase(context: Awaited<ReturnType<PortalPreviewService["require"]>>) { if (context.caseId) return context.caseId; const item = await this.prisma.case.findFirst({ where: { tenantId: context.tenantId, debtorPartyId: context.partyId, deletedAt: null }, orderBy: { updatedAt: "desc" }, select: { id: true } }); if (!item) throw new NotFoundException("Für diesen Schuldner ist keine Inkassoakte verfügbar."); return item.id; }
  private async debtorCaseRecord(id: string, tenantId: string, partyId: string) { const item = await this.prisma.case.findFirst({ where: { id, tenantId, debtorPartyId: partyId, deletedAt: null }, select: { id: true, caseNumber: true, clientParty: { select: { displayName: true } }, claim: { select: { principalAmount: true, currency: true } } } }); if (!item) throw new NotFoundException("Inkassoakte wurde nicht gefunden."); return item; }
  private async party(id: string, tenantId: string) { const item = await this.prisma.party.findFirst({ where: { id, tenantId, deletedAt: null }, select: { displayName: true } }); if (!item) throw new NotFoundException("Partei wurde nicht gefunden."); return item; }
  private async ledgerSummary(caseId: string, tenantId: string) { const entries = await this.prisma.caseLedgerEntry.findMany({ where: { caseId, tenantId, status: LedgerEntryStatus.ACTIVE }, include: { targetAllocations: { where: { status: PaymentAllocationStatus.ACTIVE } }, paymentAllocations: { where: { status: PaymentAllocationStatus.ACTIVE } } } }); let principal = new Prisma.Decimal(0), costs = new Prisma.Decimal(0), interest = new Prisma.Decimal(0), payments = new Prisma.Decimal(0), unallocated = new Prisma.Decimal(0); for (const item of entries) { const allocated = item.targetAllocations.reduce((sum, allocation) => sum.plus(allocation.amount), new Prisma.Decimal(0)); if (item.side === LedgerEntrySide.DEBIT) { const open = Prisma.Decimal.max(0, item.amount.minus(allocated)); if (item.type === LedgerEntryType.PRINCIPAL) principal = principal.plus(open); else if (item.type === LedgerEntryType.INTEREST) interest = interest.plus(open); else if (costTypes.has(item.type)) costs = costs.plus(open); } if (item.type === LedgerEntryType.PAYMENT) { payments = payments.plus(item.amount); const used = item.paymentAllocations.reduce((sum, allocation) => sum.plus(allocation.amount), new Prisma.Decimal(0)); unallocated = unallocated.plus(Prisma.Decimal.max(0, item.amount.minus(used))); } } return { openPrincipal: principal.toFixed(2), openCosts: costs.toFixed(2), openInterest: interest.toFixed(2), totalOpen: principal.plus(costs).plus(interest).toFixed(2), payments: payments.toFixed(2), unallocatedPayments: unallocated.toFixed(2) }; }
  private async documents(caseId: string, tenantId: string, visibility: PortalVisibility[]) { return this.prisma.caseDocument.findMany({ where: { caseId, tenantId, status: { not: DocumentStatus.VOIDED }, portalVisibility: { in: visibility } }, select: { id: true, filename: true, type: true, generatedAt: true } }); }
  private async paymentInformation(tenantId: string, caseNumber: string) { const settings = await this.prisma.tenantDocumentSettings.findUnique({ where: { tenantId }, select: { companyName: true, iban: true, bic: true, bankName: true } }); return settings?.iban ? { recipient: settings.companyName, iban: settings.iban, bic: settings.bic, bankName: settings.bankName, reference: caseNumber } : null; }
}
