"use client";

import * as Dialog from "@radix-ui/react-dialog";
import { Loader2, Plus } from "lucide-react";
import * as React from "react";

import { Button } from "@/components/ui/button";
import { clientContactsApi, type ClientContact, type ClientContactInput, type PortalActivation } from "./party-api";

const blank: ClientContactInput = { firstName: "", lastName: "", position: "", email: "", phone: "", mobile: "", isPrimary: false, isActive: true };
const statusLabel: Record<string, string> = { PENDING_ACTIVATION: "Aktivierung ausstehend", ACTIVE: "Aktiv", LOCKED: "Gesperrt" };

export function ClientContacts({ clientId }: { clientId: string }) {
  const [contacts, setContacts] = React.useState<ClientContact[]>([]);
  const [error, setError] = React.useState("");
  const [loading, setLoading] = React.useState(true);
  const [editing, setEditing] = React.useState<ClientContact | null | undefined>(undefined);
  const [activation, setActivation] = React.useState<PortalActivation | null>(null);
  const load = React.useCallback(async () => {
    setLoading(true);
    try { setContacts(await clientContactsApi.list(clientId)); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Ansprechpartner konnten nicht geladen werden."); } finally { setLoading(false); }
  }, [clientId]);
  React.useEffect(() => { void load(); }, [load]);
  const action = async (contact: ClientContact, name: "create" | "reissue" | "suspend" | "reactivate") => {
    setError("");
    try {
      if (name === "create") setActivation((await clientContactsApi.createPortalAccount(clientId, contact.id)).activation);
      if (name === "reissue" && contact.portalAccount) setActivation(await clientContactsApi.reissue(contact.portalAccount.id));
      if (name === "suspend" && contact.portalAccount) await clientContactsApi.suspend(contact.portalAccount.id);
      if (name === "reactivate" && contact.portalAccount) await clientContactsApi.reactivate(contact.portalAccount.id);
      await load();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Aktion konnte nicht ausgeführt werden."); }
  };
  return <section className="rounded-xl border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Ansprechpartner</h3><p className="mt-1 text-sm text-muted-foreground">Portalzugänge sind einzelnen Ansprechpartnern zugeordnet.</p></div><Button onClick={() => setEditing(null)}><Plus className="size-4" /> Ansprechpartner anlegen</Button></div>{error ? <p className="mt-3 text-sm text-destructive">{error}</p> : null}{loading ? <p className="mt-4 text-sm text-muted-foreground">Ansprechpartner werden geladen …</p> : contacts.length ? <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase text-muted-foreground"><tr><th className="px-2 py-3">Name</th><th className="px-2 py-3">Funktion</th><th className="px-2 py-3">E-Mail / Telefon</th><th className="px-2 py-3">Hauptansprechpartner</th><th className="px-2 py-3">Portalzugang</th><th className="px-2 py-3" /></tr></thead><tbody>{contacts.map((contact) => <tr className="border-b last:border-0" key={contact.id}><td className="px-2 py-3 font-medium">{contact.firstName} {contact.lastName}{!contact.isActive ? <span className="ml-2 text-xs text-muted-foreground">inaktiv</span> : null}</td><td className="px-2 py-3">{contact.position || "—"}</td><td className="px-2 py-3">{contact.email || "—"}<br />{contact.phone || contact.mobile || ""}</td><td className="px-2 py-3">{contact.isPrimary ? "Ja" : "—"}</td><td className="px-2 py-3">{contact.portalAccount ? statusLabel[contact.portalAccount.status] : "Kein Zugang"}</td><td className="px-2 py-3"><div className="flex flex-wrap justify-end gap-2"><Button onClick={() => setEditing(contact)} variant="outline">Bearbeiten</Button>{contact.isActive && !contact.portalAccount ? <Button disabled={!contact.email} onClick={() => void action(contact, "create")}>Portalzugang anlegen</Button> : null}{contact.portalAccount?.status === "PENDING_ACTIVATION" ? <Button onClick={() => void action(contact, "reissue")} variant="outline">Aktivierung neu ausstellen</Button> : null}{contact.portalAccount?.status === "ACTIVE" ? <Button onClick={() => void action(contact, "suspend")} variant="outline">Sperren</Button> : null}{contact.portalAccount?.status === "LOCKED" && contact.isActive ? <Button onClick={() => void action(contact, "reactivate")} variant="outline">Freigeben</Button> : null}</div></td></tr>)}</tbody></table></div> : <p className="mt-4 text-sm text-muted-foreground">Noch keine Ansprechpartner hinterlegt.</p>}<ContactDialog clientId={clientId} contact={editing} onDone={() => { setEditing(undefined); void load(); }} onOpenChange={(open) => !open && setEditing(undefined)} />{activation ? <ActivationDialog activation={activation} onClose={() => setActivation(null)} /> : null}</section>;
}

function ContactDialog({ clientId, contact, onDone, onOpenChange }: { clientId: string; contact: ClientContact | null | undefined; onDone: () => void; onOpenChange: (open: boolean) => void }) {
  const open = contact !== undefined; const [values, setValues] = React.useState<ClientContactInput>(blank); const [error, setError] = React.useState(""); const [saving, setSaving] = React.useState(false);
  React.useEffect(() => setValues(contact ? { firstName: contact.firstName, lastName: contact.lastName, salutation: contact.salutation ?? "", title: contact.title ?? "", position: contact.position ?? "", email: contact.email ?? "", phone: contact.phone ?? "", mobile: contact.mobile ?? "", notes: contact.notes ?? "", isPrimary: contact.isPrimary, isActive: contact.isActive } : blank), [contact]);
  const set = <K extends keyof ClientContactInput>(key: K, value: ClientContactInput[K]) => setValues((current) => ({ ...current, [key]: value }));
  const save = async () => { if (!values.firstName.trim() || !values.lastName.trim()) return setError("Vor- und Nachname sind erforderlich."); setSaving(true); setError(""); try { if (contact) await clientContactsApi.update(clientId, contact.id, values); else await clientContactsApi.create(clientId, values); onDone(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Ansprechpartner konnte nicht gespeichert werden."); } finally { setSaving(false); } };
  return <Dialog.Root onOpenChange={onOpenChange} open={open}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-foreground/25 backdrop-blur-sm" /><Dialog.Content className="fixed left-1/2 top-1/2 z-50 max-h-[90vh] w-[calc(100%-2rem)] max-w-2xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-xl border bg-card p-6 shadow-xl"><Dialog.Title className="text-lg font-semibold">{contact ? "Ansprechpartner bearbeiten" : "Ansprechpartner anlegen"}</Dialog.Title><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Vorname"><input value={values.firstName} onChange={(e) => set("firstName", e.target.value)} /></Field><Field label="Nachname"><input value={values.lastName} onChange={(e) => set("lastName", e.target.value)} /></Field><Field label="Anrede"><input value={values.salutation ?? ""} onChange={(e) => set("salutation", e.target.value)} /></Field><Field label="Titel"><input value={values.title ?? ""} onChange={(e) => set("title", e.target.value)} /></Field><Field label="Funktion"><input value={values.position ?? ""} onChange={(e) => set("position", e.target.value)} /></Field><Field label="E-Mail"><input type="email" value={values.email ?? ""} onChange={(e) => set("email", e.target.value)} /></Field><Field label="Telefon"><input value={values.phone ?? ""} onChange={(e) => set("phone", e.target.value)} /></Field><Field label="Mobil"><input value={values.mobile ?? ""} onChange={(e) => set("mobile", e.target.value)} /></Field><label className="flex items-center gap-2 text-sm"><input checked={values.isPrimary} onChange={(e) => set("isPrimary", e.target.checked)} type="checkbox" /> Hauptansprechpartner</label><label className="flex items-center gap-2 text-sm"><input checked={values.isActive} onChange={(e) => set("isActive", e.target.checked)} type="checkbox" /> Aktiv</label></div>{error ? <p className="mt-3 text-sm text-destructive">{error}</p> : null}<div className="mt-6 flex justify-end gap-2"><Dialog.Close asChild><Button disabled={saving} variant="outline">Abbrechen</Button></Dialog.Close><Button disabled={saving} onClick={() => void save()}>{saving ? <><Loader2 className="size-4 animate-spin" /> Speichert …</> : "Speichern"}</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1 text-sm"><span>{label}</span>{React.isValidElement(children) ? React.cloneElement(children as React.ReactElement<{ className?: string }>, { className: "h-10 rounded-lg border bg-background px-3" }) : children}</label>; }
function ActivationDialog({ activation, onClose }: { activation: PortalActivation; onClose: () => void }) { return <Dialog.Root onOpenChange={(open) => !open && onClose()} open><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-foreground/25" /><Dialog.Content className="fixed left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 rounded-xl border bg-card p-6 shadow-xl"><Dialog.Title className="text-lg font-semibold">Aktivierungsdaten</Dialog.Title><p className="mt-2 text-sm text-muted-foreground">Diese Aktivierungsdaten werden aus Sicherheitsgründen nur einmal angezeigt.</p><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-muted-foreground">Portal-Kennung</dt><dd className="font-mono font-medium">{activation.loginIdentifier}</dd></div><div><dt className="text-muted-foreground">Aktivierungslink</dt><dd className="break-all font-medium">{activation.activationUrl}</dd></div><div><dt className="text-muted-foreground">Gültig bis</dt><dd>{new Intl.DateTimeFormat("de-DE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(activation.expiresAt))}</dd></div></dl><div className="mt-6 flex justify-end"><Button onClick={onClose}>Verstanden</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root>; }
