import { Building2, CircleHelp, LockKeyhole } from "lucide-react";
import Link from "next/link";

import { PageHero, PrimaryLink, SecondaryLink } from "@/components/public-site/public-elements";
import { PublicShell } from "@/components/public-site/public-shell";
import { publicMetadata } from "@/lib/public-metadata";

export const metadata = publicMetadata("Kontakt", "Die passenden Kontakt- und Portalwege für Unternehmen und Schuldner bei payveo.", "/kontakt");

export default function ContactPage(){return <PublicShell><PageHero description="Wählen Sie den Kontaktweg, der zu Ihrem Anliegen passt. Vorgangsbezogene Informationen gehören ausschließlich in den geschützten Portalbereich." eyebrow="Kontakt" title="Ihr Anliegen auf dem richtigen Weg" /><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="grid gap-6 lg:grid-cols-3"><article className="rounded-3xl border border-slate-200 p-8"><Building2 className="size-7 text-[#007FC5]" /><h2 className="mt-6 text-xl font-semibold">Bestehende Mandanten</h2><p className="mt-3 text-sm leading-6 text-slate-600">Übermitteln Sie neue Forderungen und rufen Sie vorhandene Vorgänge über Ihren geschützten Zugang auf.</p><div className="mt-7"><PrimaryLink href="/portal/login">Mandantenportal</PrimaryLink></div></article><article className="rounded-3xl border border-slate-200 p-8"><LockKeyhole className="size-7 text-[#007FC5]" /><h2 className="mt-6 text-xl font-semibold">Schuldner mit Schreiben</h2><p className="mt-3 text-sm leading-6 text-slate-600">Nutzen Sie die Login-ID aus Ihren Unterlagen, um Ihren Vorgang geschützt aufzurufen.</p><div className="mt-7"><PrimaryLink href="/portal/login">Schuldnerportal</PrimaryLink></div></article><article className="rounded-3xl border border-slate-200 p-8"><CircleHelp className="size-7 text-[#007FC5]" /><h2 className="mt-6 text-xl font-semibold">Zusammenarbeit anfragen</h2><p className="mt-3 text-sm leading-6 text-slate-600">Allgemeine Kontaktdaten werden vor der Veröffentlichung ausschließlich aus verifizierten Unternehmensangaben ergänzt.</p><div className="mt-7"><SecondaryLink href="/fuer-unternehmen">Zusammenarbeit kennenlernen</SecondaryLink></div></article></div><aside className="mt-12 rounded-3xl bg-[#f5f9fc] p-7 text-sm leading-6 text-slate-600"><strong className="text-slate-900">Datenschutz:</strong> Bitte übermitteln Sie keine sensiblen Forderungs- oder Personendaten über ungeschützte Kontaktwege. Verwenden Sie hierfür ausschließlich den vorgesehenen Portalzugang. Weitere Informationen finden Sie unter <Link className="font-semibold text-[#007FC5] underline-offset-4 hover:underline" href="/rechtliches/datenschutz">Datenschutz</Link>.</aside></section></PublicShell>}
