import { Eye, Gauge, MessageCircle, ShieldCheck, Waypoints } from "lucide-react";

import { CtaSection, PageHero, SectionIntro } from "@/components/public-site/public-elements";
import { PublicShell } from "@/components/public-site/public-shell";
import { publicMetadata } from "@/lib/public-metadata";

export const metadata = publicMetadata("Über payveo", "Anspruch und Arbeitsweise von payveo im professionellen Forderungsmanagement.", "/ueber-payveo");

export default function AboutPage(){const principles=[[Eye,"Klarheit","Sachverhalte, Beträge und nächste Schritte sollen für die Beteiligten verständlich eingeordnet werden."],[Waypoints,"Nachvollziehbarkeit","Bearbeitungsstände, Kontakte und Zahlungen werden geordnet dokumentiert und im richtigen Kontext betrachtet."],[Gauge,"Effizienz","Klare Abläufe helfen dabei, Vorgänge konzentriert zu bearbeiten, ohne die fachliche Einzelfallprüfung zu ersetzen."],[MessageCircle,"Respekt","Ein professioneller Umgang bleibt auch dann wichtig, wenn Interessen konsequent vertreten werden."],[ShieldCheck,"Verbindlichkeit","Fristen, Vereinbarungen und Entscheidungen werden nicht dem Zufall überlassen, sondern strukturiert begleitet."]] as const;return <PublicShell><PageHero description="payveo steht für eine moderne Forderungsbearbeitung, die konsequente Abläufe mit verständlicher Kommunikation und einem respektvollen Umgang verbindet." eyebrow="Über payveo" title="Professionell arbeiten. Verantwortungsvoll kommunizieren." /><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><SectionIntro description="Wir möchten Forderungsmanagement so gestalten, dass Mandanten den Verlauf ihrer Vorgänge nachvollziehen können und Schuldner klare Informationen zu ihrem Fall erhalten." eyebrow="Arbeitsweise" title="Unser Anspruch an jeden Vorgang" /><div className="mt-14 grid gap-px overflow-hidden rounded-3xl border border-slate-200 bg-slate-200 md:grid-cols-2 lg:grid-cols-3">{principles.map(([Icon,title,text])=><article className="bg-white p-8" key={title}><Icon className="size-6 text-[#007FC5]" /><h2 className="mt-5 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></section><section className="bg-slate-950 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:py-24"><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">Digitale Abläufe sind Mittel zum Zweck.</h2><p className="text-lg leading-8 text-slate-300">Sie helfen, Informationen geordnet verfügbar zu machen, Bearbeitungsstände transparent zu halten und Kommunikation zuverlässig zu dokumentieren. Im Mittelpunkt bleibt die fachlich angemessene Bearbeitung des einzelnen Vorgangs.</p></div></section><CtaSection description="Informieren Sie sich über die Zusammenarbeit oder nutzen Sie Ihren bestehenden Portalzugang." primary={["Für Unternehmen","/fuer-unternehmen"]} secondary={["Kontakt","/kontakt"]} title="Mehr über payveo erfahren" /></PublicShell>}
