import { FileSearch, HandCoins, Landmark, MapPinCheck, MessageSquareText, Scale, Waypoints, WalletCards } from "lucide-react";

import { CtaSection, PageHero, SectionIntro } from "@/components/public-site/public-elements";
import { PublicShell } from "@/components/public-site/public-shell";
import { publicMetadata } from "@/lib/public-metadata";

export const metadata = publicMetadata("Leistungen", "Strukturierte Forderungsbearbeitung, Zahlungsmanagement und nachvollziehbare Kommunikation mit payveo.", "/leistungen");

const sections = [
  [FileSearch, "Außergerichtliche Forderungsbearbeitung", "Wir ordnen die übergebenen Forderungsdaten, prüfen den Bearbeitungsstand und führen die außergerichtliche Kommunikation strukturiert fort.", ["Nachvollziehbare Vorgangsführung", "Schriftliche Zahlungsaufforderungen", "Dokumentierte Kommunikation und Fristen"]],
  [WalletCards, "Zahlungsmanagement", "Zahlungseingänge und Vereinbarungen werden dem jeweiligen Vorgang zugeordnet und im weiteren Verlauf berücksichtigt.", ["Überwachung eingehender Zahlungen", "Nachvollziehbare Zahlungszuordnung", "Ratenvereinbarungen und deren Fälligkeiten"]],
  [HandCoins, "Ratenvereinbarungen", "Wenn eine sofortige Zahlung nicht möglich ist, können tragfähige Ratenlösungen geprüft, dokumentiert und in ihrem Verlauf begleitet werden.", ["Ratenanfragen geordnet prüfen", "Fälligkeiten nachvollziehbar festhalten", "Erfüllung und Abweichungen beobachten"]],
  [MessageSquareText, "Kommunikation", "Eine klare, sachliche Ansprache schafft Orientierung und ermöglicht es, Rückfragen oder Lösungsmöglichkeiten geordnet zu bearbeiten.", ["Schriftliche und dokumentierte Kontakte", "Verständliche Darstellung des Vorgangs", "Respektvoller Umgang mit Schuldnern"]],
  [Landmark, "Gerichtliche Schritte", "Bleibt eine außergerichtliche Lösung aus, können gerichtliche Schritte im Rahmen der jeweiligen Voraussetzungen vorbereitet und bewertet werden.", ["Vorbereitung des gerichtlichen Mahnverfahrens", "Dokumentation des Forderungsstands", "Keine pauschale oder automatische Eskalation"]],
  [Scale, "Titulierte Forderungen und Vollstreckung", "Bestehende Titel und mögliche Vollstreckungsmaßnahmen werden fallbezogen dokumentiert und für die weitere Bearbeitung vorbereitet.", ["Erfassung vorhandener Titel", "Forderungsstand als Entscheidungsgrundlage", "Vorbereitung geeigneter weiterer Maßnahmen"]],
  [MapPinCheck, "Adressklärung", "Wenn eine aktuelle Anschrift fehlt, kann eine kontrollierte Adressklärung als eigener Bearbeitungsschritt dokumentiert werden.", ["Nachvollziehbarer Rechercheauftrag", "Prüfung gefundener Anschriften", "Kontrollierte Übernahme neuer Adressdaten"]],
  [Waypoints, "Mandanteninformation", "Bestehende Mandanten erhalten einen nachvollziehbaren Einblick in ihre übergebenen Vorgänge und wesentliche Bearbeitungsstände.", ["Geschützter Portalzugang", "Vorgänge geordnet einsehen", "Bearbeitungsstand im Zusammenhang verstehen"]],
] as const;

export default function ServicesPage() {
  return <PublicShell><PageHero description="Forderungsmanagement besteht aus mehr als einzelnen Mahnschreiben. Entscheidend sind belastbare Daten, ein klarer Bearbeitungsstand und angemessene nächste Schritte." eyebrow="Leistungen" title="Forderungen entlang ihres Verlaufs bearbeiten" /><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><SectionIntro description="Welche Maßnahme sinnvoll ist, richtet sich nach dem konkreten Vorgang. Eine fachliche Prüfung steht vor jeder weiteren Eskalation." title="Leistungen mit klarer Einordnung" /><div className="mt-12 divide-y divide-slate-200 border-y border-slate-200">{sections.map(([Icon,title,text,items],index)=><article className="grid gap-6 py-9 lg:grid-cols-[4rem_1fr_1fr] lg:gap-10" key={title}><div><Icon className="size-6 text-[#007FC5]" /></div><div><p className="text-sm font-semibold text-[#007FC5]">{String(index+1).padStart(2,"0")}</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">{title}</h2><p className="mt-4 leading-7 text-slate-600">{text}</p></div><ul className="space-y-3 lg:pt-8">{items.map(item=><li className="border-l-2 border-[#007FC5] pl-3 text-sm leading-6 text-slate-700" key={item}>{item}</li>)}</ul></article>)}</div></section><CtaSection description="Bestehende Mandanten übermitteln neue Vorgänge über ihren geschützten Zugang." primary={["Zum Mandantenportal","/portal/login"]} secondary={["Für Unternehmen","/fuer-unternehmen"]} title="Forderungen geordnet übergeben" /></PublicShell>;
}
