import { ArrowRight, CircleCheck, FileText, Handshake, Landmark, MessageSquareText, SearchCheck, WalletCards } from "lucide-react";
import Link from "next/link";

import { CtaSection, PrimaryLink, SecondaryLink, SectionIntro } from "./public-elements";

const services = [
  [FileText, "Außergerichtliche Bearbeitung", "Forderungen werden strukturiert geprüft, dokumentiert und mit klaren nächsten Schritten bearbeitet."],
  [MessageSquareText, "Kommunikation mit Augenmaß", "Verbindliche Ansprache und nachvollziehbare Korrespondenz – sachlich, respektvoll und lösungsorientiert."],
  [WalletCards, "Zahlungsmanagement", "Zahlungseingänge, Vereinbarungen und offene Beträge werden fortlaufend überwacht und zugeordnet."],
  [Landmark, "Gerichtliche Schritte", "Wenn eine außergerichtliche Lösung ausbleibt, können weitere Schritte kontrolliert vorbereitet und bewertet werden."],
] as const;

export function PublicHome() {
  return <>
    <section className="relative overflow-hidden border-b border-slate-200 bg-[#f5f9fc]"><div aria-hidden className="absolute inset-y-0 right-0 hidden w-[38%] bg-[#007FC5] lg:block" /><div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 sm:py-24 lg:grid-cols-[1.25fr_0.75fr] lg:py-32"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#007FC5]">Professionelles Forderungsmanagement</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-[1.02] tracking-[-0.045em] text-slate-950 sm:text-6xl lg:text-7xl">Forderungen konsequent bearbeiten. Fair im Umgang.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">payveo unterstützt Unternehmen bei einer klaren, strukturierten und zeitgemäßen Forderungsbearbeitung – vom ersten Vorgang bis zur transparenten Nachverfolgung.</p><div className="mt-9 flex flex-wrap gap-3"><PrimaryLink href="/fuer-unternehmen">Zusammenarbeit kennenlernen</PrimaryLink><SecondaryLink href="/portal/login">Zum Schuldnerportal</SecondaryLink></div></div><div className="relative self-end rounded-[2rem] bg-slate-950 p-7 text-white shadow-2xl shadow-slate-900/15 sm:p-9 lg:-ml-8"><p className="text-sm font-semibold text-[#38a9e8]">Klarer Prozess</p><ol className="mt-6 space-y-5">{["Forderung strukturiert übernehmen", "Sachverhalt und nächsten Schritt prüfen", "Kommunikation und Zahlungen begleiten", "Bearbeitungsstand nachvollziehbar halten"].map((item,index)=><li className="flex gap-4" key={item}><span className="grid size-8 shrink-0 place-items-center rounded-full border border-white/20 text-sm font-semibold">{index+1}</span><span className="pt-1 text-sm leading-6 text-slate-200">{item}</span></li>)}</ol></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><SectionIntro description="Wir verbinden fachlich geordnete Abläufe mit verständlicher Kommunikation. Mandanten behalten den Bearbeitungsstand im Blick; Schuldner erhalten einen klaren Zugang zu ihrem Vorgang." eyebrow="Unser Anspruch" title="Nachvollziehbar für alle Beteiligten" /><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-slate-200 bg-slate-200 md:grid-cols-3">{[[SearchCheck,"Klarheit","Jeder Vorgang folgt einem dokumentierten Bearbeitungsstand und nachvollziehbaren nächsten Schritten."],[Handshake,"Respekt","Konsequente Forderungsbearbeitung und ein angemessener Umgang mit Schuldnern gehören für uns zusammen."],[CircleCheck,"Verbindlichkeit","Absprachen, Zahlungen und Fristen werden strukturiert verfolgt und transparent eingeordnet."]].map(([Icon,title,text])=><article className="bg-white p-7 sm:p-8" key={String(title)}><Icon className="size-6 text-[#007FC5]" /><h3 className="mt-5 text-xl font-semibold">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{String(text)}</p></article>)}</div></section>

    <section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.14em] text-[#38a9e8]">Leistungen</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-[-0.025em] sm:text-4xl">Vom offenen Vorgang zur strukturierten Bearbeitung</h2></div><Link className="inline-flex items-center gap-2 text-sm font-semibold text-[#38a9e8]" href="/leistungen">Alle Leistungen ansehen <ArrowRight className="size-4" /></Link></div><div className="mt-12 grid gap-5 md:grid-cols-2">{services.map(([Icon,title,text])=><article className="rounded-3xl border border-slate-800 bg-slate-900 p-7" key={title}><Icon className="size-6 text-[#38a9e8]" /><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-300">{text}</p></article>)}</div></div></section>

    <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:items-center lg:py-28"><div><SectionIntro description="Forderungen lassen sich über den bestehenden Mandantenzugang digital übermitteln. Bearbeitungsstände und Vorgänge bleiben nachvollziehbar, ohne technische Details in den Vordergrund zu stellen." eyebrow="Für Unternehmen" title="Forderungsmanagement, das sich in klare Abläufe einfügt" /><div className="mt-8"><PrimaryLink href="/fuer-unternehmen">Zusammenarbeit im Überblick</PrimaryLink></div></div><div className="rounded-3xl border border-slate-200 bg-[#f5f9fc] p-8 sm:p-10"><h3 className="text-xl font-semibold">Mandantenportal</h3><p className="mt-3 leading-7 text-slate-600">Bestehende Mandanten können neue Forderungen übermitteln und den Status ihrer Vorgänge nachvollziehen.</p><Link className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#007FC5]" href="/portal/login">Zum Mandantenportal <ArrowRight className="size-4" /></Link></div></section>

    <section className="border-y border-slate-200 bg-[#f5f9fc]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div className="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><p className="text-sm font-semibold text-[#007FC5]">Sie haben ein Schreiben von payveo erhalten?</p><p className="mt-3 text-sm leading-6 text-slate-600">Im Schuldnerportal können Sie die für Sie freigegebenen Informationen zu Ihrem Vorgang aufrufen.</p><div className="mt-6"><PrimaryLink href="/portal/login">Zum Schuldnerportal</PrimaryLink></div></div><SectionIntro description="Offene Forderungen sind häufig mit Fragen verbunden. Deshalb stellen wir Informationen verständlich bereit und ermöglichen einen geschützten Zugang zu Dokumenten, Zahlungen und bestehenden Vereinbarungen." eyebrow="Für Schuldner" title="Klarheit zum eigenen Vorgang" /></div></section>

    <CtaSection description="Erfahren Sie, wie Forderungen übergeben, bearbeitet und transparent begleitet werden." primary={["Für Unternehmen", "/fuer-unternehmen"]} secondary={["Kontaktwege", "/kontakt"]} title="Forderungsmanagement strukturiert angehen" />
  </>;
}
