import { FileText, HandCoins, ListChecks, WalletCards } from "lucide-react";

import { CtaSection, PageHero, PrimaryLink, SectionIntro } from "@/components/public-site/public-elements";
import { PublicShell } from "@/components/public-site/public-shell";
import { publicMetadata } from "@/lib/public-metadata";

export const metadata = publicMetadata("Für Schuldner", "Informationen für Personen und Unternehmen, die ein Schreiben von payveo erhalten haben.", "/fuer-schuldner");

export default function DebtorsPublicPage(){const items=[[ListChecks,"Vorgang einsehen","Rufen Sie die für Sie freigegebenen Angaben zu Ihrem Vorgang geschützt auf."],[FileText,"Dokumente prüfen","Sehen Sie bereitgestellte Schreiben und Unterlagen an einem zentralen Ort ein."],[WalletCards,"Zahlungen nachvollziehen","Behalten Sie dokumentierte Zahlungen und den aktuellen Forderungsstand im Blick."],[HandCoins,"Ratenvereinbarung","Sehen Sie bestehende Ratenpläne ein oder nutzen Sie die angebotene Möglichkeit für eine Ratenanfrage."]] as const;return <PublicShell><PageHero description="Ein offener Forderungsvorgang wirft häufig Fragen auf. Im geschützten Schuldnerportal finden Sie die für Ihren Fall freigegebenen Informationen und Dokumente." eyebrow="Für Schuldner" title="Sie haben ein Schreiben von payveo erhalten?"><PrimaryLink href="/portal/login">Vorgang im Portal aufrufen</PrimaryLink></PageHero><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><SectionIntro description="Bitte halten Sie die Login-ID aus Ihren Unterlagen und Ihr persönliches Passwort bereit. Falls Ihr Zugang noch nicht aktiviert ist, können Sie die Aktivierung auf der Loginseite starten." eyebrow="Schuldnerportal" title="Ihr geschützter Zugang zum Vorgang" /><div className="mt-14 grid gap-5 md:grid-cols-2">{items.map(([Icon,title,text])=><article className="flex gap-5 rounded-3xl border border-slate-200 p-7" key={title}><div className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#e5f4fb] text-[#007FC5]"><Icon className="size-5" /></div><div><h2 className="text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div></article>)}</div><div className="mt-12 rounded-3xl bg-[#f5f9fc] p-8 sm:p-10"><h2 className="text-2xl font-semibold">Sachlich klären statt vorschnell reagieren</h2><p className="mt-4 max-w-3xl leading-7 text-slate-600">Prüfen Sie die Angaben in Ruhe. Wenn etwas unklar ist, beziehen Sie sich bei einer Kontaktaufnahme bitte auf das payveo-Aktenzeichen aus Ihrem Schreiben. Sensible Vorgangsdaten werden nicht öffentlich angezeigt.</p></div></section><CtaSection description="Melden Sie sich mit Ihrer Login-ID und Ihrem persönlichen Passwort an. Die Aktivierung eines neuen Zugangs erfolgt ebenfalls über die bestehende Portalseite." primary={["Zum Schuldnerportal","/portal/login"]} title="Vorgang sicher aufrufen" /></PublicShell>}
