"use client";

import Link from "next/link";
import * as React from "react";
import { caseApi } from "@/components/cases/case-api";
import { formatCurrency, formatDate } from "@/components/cases/case-ui";
import { installmentPlanItemStatusLabels, installmentPlanStatusLabels, type InstallmentPlan } from "@/types/installment-plan";

export function InstallmentPlanDetail({ id }: { id: string }) {
  const [plan, setPlan] = React.useState<InstallmentPlan | null>(null); const [error, setError] = React.useState(""); const [pending, setPending] = React.useState(false);
  const load = React.useCallback(async () => { try { setPlan(await caseApi.getInstallmentPlan(id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Ratenplan konnte nicht geladen werden."); } }, [id]);
  React.useEffect(() => { void load(); }, [load]);
  const action = async (kind: "activate" | "cancel" | "default") => { setPending(true); setError(""); try { const next = kind === "activate" ? await caseApi.activateInstallmentPlan(id) : kind === "cancel" ? await caseApi.cancelInstallmentPlan(id) : await caseApi.defaultInstallmentPlan(id); setPlan(next); } catch (cause) { setError(cause instanceof Error ? cause.message : "Aktion nicht möglich."); } finally { setPending(false); } };
  if (!plan) return <p>{error || "Laden …"}</p>;
  return <section className="space-y-6"><Link className="text-sm text-primary hover:underline" href="/ratenanfragen">← Ratenanfragen</Link><h1 className="text-3xl font-semibold">Ratenplan {plan.case?.caseNumber}</h1>{error?<p className="text-destructive">{error}</p>:null}<div className="grid gap-4 rounded-xl border bg-card p-5 sm:grid-cols-3"><p>Status<br/><strong>{installmentPlanStatusLabels[plan.status]}</strong></p><p>Planbetrag<br/><strong>{formatCurrency(plan.initialOpenAmount,"EUR")}</strong></p><p>Aktuell offen<br/><strong>{formatCurrency(plan.currentCaseBalance,"EUR")}</strong></p><p>Rate<br/><strong>{formatCurrency(plan.plannedInstallmentAmount,"EUR")}</strong></p><p>Start<br/><strong>{formatDate(plan.startDate)}</strong></p><p>Raten<br/><strong>{plan.numberOfInstallments}</strong></p></div>{plan.status==="DRAFT"?<button className="rounded-lg bg-primary px-3 py-2 text-primary-foreground disabled:opacity-50" disabled={pending} onClick={()=>void action("activate")}>Ratenplan aktivieren</button>:null}{plan.status==="ACTIVE"?<div className="flex gap-2"><button className="rounded-lg border px-3 py-2 disabled:opacity-50" disabled={pending} onClick={()=>void action("cancel")}>Stornieren</button><button className="rounded-lg border px-3 py-2 disabled:opacity-50" disabled={pending} onClick={()=>void action("default")}>Als gescheitert markieren</button></div>:null}<div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-3">Nr.</th><th>Fälligkeit</th><th>Soll</th><th>Angerechnet</th><th>Rest</th><th>Status</th></tr></thead><tbody>{plan.items.map(item=><tr className="border-b last:border-0" key={item.id}><td className="p-3">{item.sequenceNumber}</td><td>{formatDate(item.dueDate)}</td><td>{formatCurrency(item.plannedAmount,"EUR")}</td><td>{formatCurrency(item.creditedAmount,"EUR")}</td><td>{formatCurrency(item.remainingAmount,"EUR")}</td><td>{installmentPlanItemStatusLabels[item.status]}</td></tr>)}</tbody></table></div><p className="text-sm text-muted-foreground">Der Ratenplan basiert auf dem bei Erstellung offenen Betrag. Weitere Zinsen oder Kosten können die aktuelle offene Gesamtforderung verändern.</p></section>;
}
