"use client";
import Link from "next/link";
import * as React from "react";
import { caseApi } from "@/components/cases/case-api";
import { formatCurrency, formatDate } from "@/components/cases/case-ui";
import { installmentRequestStatusLabels, type InstallmentRequest } from "@/types/installment-request";
export function InstallmentRequestsClient({ id }: { id?: string }) {
 const [items,setItems]=React.useState<InstallmentRequest[]>([]); const [detail,setDetail]=React.useState<InstallmentRequest|null>(null); const [planId,setPlanId]=React.useState<string|null>(null); const [pending,setPending]=React.useState(false); const [error,setError]=React.useState("");
 const load=React.useCallback(async()=>{try { if(id) setDetail(await caseApi.getInstallmentRequest(id)); else setItems(await caseApi.getInstallmentRequests()); } catch(e){setError(e instanceof Error?e.message:"Ratenanfragen konnten nicht geladen werden.");}},[id]);
 React.useEffect(()=>{void load()},[load]);
 const action=async(kind:"review"|"approve"|"reject")=>{if(!detail)return; try { const next=kind==="review"?await caseApi.reviewInstallmentRequest(detail.id):kind==="approve"?await caseApi.approveInstallmentRequest(detail.id):await caseApi.rejectInstallmentRequest(detail.id);setDetail(next);}catch(e){setError(e instanceof Error?e.message:"Aktion nicht möglich.")}};
 const createPlan=async()=>{if(!detail)return;setPending(true);setError("");try{const plan=await caseApi.createInstallmentPlan(detail.id);setPlanId(plan.id);}catch(e){setError(e instanceof Error?e.message:"Ratenplan konnte nicht erstellt werden.");}finally{setPending(false)}};
 if(id) return <section className="space-y-6"><Link className="text-sm text-primary hover:underline" href="/ratenanfragen">← Ratenanfragen</Link>{error?<p className="text-destructive">{error}</p>:null}{!detail?<p>Laden …</p>:<><h1 className="text-3xl font-semibold">Ratenanfrage</h1><div className="grid gap-4 rounded-xl border bg-card p-5 sm:grid-cols-2"><p>Aktenzeichen<br/><strong>{detail.case?.caseNumber}</strong></p><p>Schuldner<br/><strong>{detail.case?.debtorParty.displayName}</strong></p><p>Monatsrate<br/><strong>{formatCurrency(detail.requestedMonthlyAmount,"EUR")}</strong></p><p>Starttermin<br/><strong>{formatDate(detail.preferredStartDate)}</strong></p><p>Status<br/><strong>{installmentRequestStatusLabels[detail.status]}</strong></p><p>Nachricht<br/><strong>{detail.debtorMessage||"—"}</strong></p></div>{detail.status==="SUBMITTED"||detail.status==="UNDER_REVIEW"?<div className="flex gap-2">{detail.status==="SUBMITTED"?<button className="rounded-lg border px-3 py-2" onClick={()=>void action("review")}>In Prüfung setzen</button>:null}<button className="rounded-lg bg-primary px-3 py-2 text-primary-foreground" onClick={()=>void action("approve")}>Genehmigen</button><button className="rounded-lg border px-3 py-2" onClick={()=>void action("reject")}>Ablehnen</button></div>:detail.status==="APPROVED"?<div className="flex items-center gap-3"><button className="rounded-lg bg-primary px-3 py-2 text-primary-foreground disabled:opacity-50" disabled={pending} onClick={()=>void createPlan()}>{pending?"Erstelle …":"Ratenplan erstellen"}</button>{planId?<Link className="text-primary hover:underline" href={`/ratenplaene/${planId}`}>Planvorschau öffnen</Link>:null}</div>:null}</>}</section>;
 return <section><h1 className="text-3xl font-semibold">Ratenanfragen</h1>{error?<p className="mt-4 text-destructive">{error}</p>:null}<div className="mt-6 space-y-3">{items.map(item=><Link className="block rounded-xl border bg-card p-4 hover:bg-muted/50" href={`/ratenanfragen/${item.id}`} key={item.id}><strong>{item.case?.debtorParty.displayName} · {item.case?.caseNumber}</strong><p className="mt-1 text-sm text-muted-foreground">{formatCurrency(item.requestedMonthlyAmount,"EUR")} ab {formatDate(item.preferredStartDate)} · {installmentRequestStatusLabels[item.status]}</p></Link>)}</div></section>;
}
