"use client";
import Link from "next/link";
import * as React from "react";
import { caseApi } from "./case-api";
import { formatCurrency, formatDate } from "./case-ui";
import { installmentPlanStatusLabels, type InstallmentPlan } from "@/types/installment-plan";

export function CaseInstallmentPlan({ caseId }: { caseId: string }) { const [plans,setPlans]=React.useState<InstallmentPlan[]>([]); React.useEffect(()=>{void caseApi.getInstallmentPlans().then(setPlans).catch(()=>setPlans([]));},[]); const plan=plans.find(item=>item.case?.id===caseId); if(!plan)return null; return <section className="rounded-2xl border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">Ratenplan</h2><p className="mt-1 text-sm text-muted-foreground">{installmentPlanStatusLabels[plan.status]}</p></div><Link className="text-sm text-primary hover:underline" href={`/ratenplaene/${plan.id}`}>Ratenplan öffnen</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Info label="Planbetrag" value={formatCurrency(plan.initialOpenAmount,"EUR")} /><Info label="Vereinbarte Rate" value={formatCurrency(plan.plannedInstallmentAmount,"EUR")} /><Info label="Aktueller Aktenstand" value={formatCurrency(plan.currentCaseBalance,"EUR")} /></div><p className="mt-4 text-sm text-muted-foreground">Nächste Rate: {plan.nextItem?`${formatCurrency(plan.nextItem.remainingAmount,"EUR")} am ${formatDate(plan.nextItem.dueDate)}`:"keine offene Rate"}</p>{plan.planCaseDifference !== "0.00" ? <p className="mt-2 text-xs text-muted-foreground">Der aktuelle Aktenstand kann vom historischen Planbetrag abweichen.</p> : null}</section>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
