export const demoCases = [
  {
    fileNumber: "0000001/2026",
    client: "Muster GmbH",
    debtor: "Max Mustermann",
    amount: "1.248,53 €",
    status: "Außergerichtlich",
    clerk: "Lucas Kindt",
    updated: "Heute",
  },
  {
    fileNumber: "0000002/2026",
    client: "Autohaus Weber",
    debtor: "Anna Schmidt",
    amount: "4.827,10 €",
    status: "Teilzahlung",
    clerk: "Lucas Kindt",
    updated: "Gestern",
  },
  {
    fileNumber: "0000003/2026",
    client: "Müller Logistik",
    debtor: "Peter Hoffmann",
    amount: "18.933,44 €",
    status: "Gerichtlich",
    clerk: "Lucas Kindt",
    updated: "03.08.2026",
  },
  {
    fileNumber: "0000004/2026",
    client: "Elektro Kaiser",
    debtor: "Lisa Becker",
    amount: "387,12 €",
    status: "Neu",
    clerk: "Lucas Kindt",
    updated: "Heute",
  },
];